/**
 * Download lesson thumbnails from the DB, optimize to WebP, and regenerate
 * the static homepage carousel manifest.
 *
 * Run after publishing new lessons: pnpm sync:carousel
 */
import "dotenv/config";
import { mkdir, readFile, readdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { asc, eq, sql } from "drizzle-orm";
import sharp from "sharp";
import { db } from "../src/db";
import { lessons } from "../src/db/schema";
import { canonicalLessonId } from "../src/lib/constants/lessons";
import { generateLessonThumbnailDataUrl } from "../src/lib/lesson-thumbnail";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(ROOT, "public", "carousel");
const MANIFEST_PATH = path.join(ROOT, "src/lib/landing/carousel-manifest.ts");

const CAROUSEL_WIDTH = 1280;
const WEBP_QUALITY = 90;

type ManifestLesson = {
  id: string;
  title: string;
  category: string;
  difficulty: string;
  estimatedMinutes: number;
  description: string;
  thumbnail: string;
  totalXp: number;
  sectionCount: number;
  subsectionCount: number;
};

function decodeDataUrl(dataUrl: string) {
  const match = dataUrl.match(/^data:([^;,]+)?(?:;charset=[^;,]+)?(;base64)?,(.*)$/i);
  if (!match) {
    throw new Error("Invalid data URL");
  }

  const [, , base64Flag, payload] = match;
  if (base64Flag) {
    return Buffer.from(payload, "base64");
  }
  return Buffer.from(decodeURIComponent(payload), "utf8");
}

function carouselFileName(slug: string) {
  return `${slug}.webp`;
}

async function readThumbnailBytes(
  thumbnail: string | null | undefined,
  fallback: { title: string; category: string; difficulty: string; description: string }
) {
  const value = thumbnail?.trim() ?? "";

  if (!value) {
    throw new Error("Empty thumbnail");
  }

  if (value.startsWith("http://") || value.startsWith("https://")) {
    const response = await fetch(value);
    if (!response.ok) {
      throw new Error(`HTTP ${response.status} for ${value.slice(0, 80)}`);
    }
    return Buffer.from(await response.arrayBuffer());
  }

  if (value.startsWith("data:")) {
    return decodeDataUrl(value);
  }

  if (value.startsWith("/")) {
    return readFile(path.join(ROOT, "public", value.replace(/^\//, "")));
  }

  throw new Error(`Unsupported thumbnail format: ${value.slice(0, 40)}`);
}

async function writeOptimizedWebp(input: Buffer, outPath: string) {
  await sharp(input)
    .rotate()
    .resize(CAROUSEL_WIDTH, Math.round((CAROUSEL_WIDTH * 9) / 16), {
      fit: "cover",
      position: "centre",
    })
    .webp({ quality: WEBP_QUALITY })
    .toFile(outPath);
}

function formatManifest(lessonsForManifest: ManifestLesson[]) {
  return `/** AUTO-GENERATED by scripts/sync-carousel-thumbnails.ts — do not edit. */
import type { LessonMeta } from "@/lib/types/lesson";

export const STATIC_CAROUSEL_LESSONS: LessonMeta[] = ${JSON.stringify(lessonsForManifest, null, 2)};

export const STATIC_CAROUSEL_SLUGS: string[] = STATIC_CAROUSEL_LESSONS.map(
  (lesson) => lesson.id
);
`;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const rows = await db
    .select({
      slug: lessons.slug,
      title: lessons.title,
      category: lessons.category,
      difficulty: lessons.difficulty,
      estimatedMinutes: lessons.estimatedMinutes,
      description: lessons.description,
      thumbnail: lessons.thumbnail,
      sectionCount: sql<number>`COALESCE(jsonb_array_length(${lessons.sections}), 0)::int`.mapWith(
        Number
      ),
      subsectionCount: sql<number>`
        COALESCE((
          SELECT SUM(jsonb_array_length(COALESCE(section.elem->'subsections', '[]'::jsonb)))
          FROM jsonb_array_elements(COALESCE(${lessons.sections}, '[]'::jsonb)) AS section(elem)
        ), 0)::int
      `.mapWith(Number),
      quizXp: sql<number>`
        COALESCE((
          SELECT SUM(COALESCE((sub.elem->'quiz'->>'xpReward')::int, 0))
          FROM jsonb_array_elements(COALESCE(${lessons.sections}, '[]'::jsonb)) AS section(elem),
               jsonb_array_elements(COALESCE(section.elem->'subsections', '[]'::jsonb)) AS sub(elem)
          WHERE sub.elem->'quiz' IS NOT NULL
        ), 0)::int
      `.mapWith(Number),
      questionsPerAttempt: sql<number>`
        COALESCE((${lessons.masteryQuiz}->>'questionsPerAttempt')::int, 5)
      `.mapWith(Number),
      masteryXpPerQuestion: sql<number>`
        COALESCE((${lessons.masteryQuiz}->'questionPool'->0->>'xpReward')::int, 30)
      `.mapWith(Number),
    })
    .from(lessons)
    .where(eq(lessons.status, "published"))
    .orderBy(asc(lessons.sortOrder), asc(lessons.slug));

  const manifest: ManifestLesson[] = [];
  let fallbackCount = 0;

  for (const row of rows) {
    const id = canonicalLessonId(row.slug);
    const outFile = carouselFileName(row.slug);
    const outPath = path.join(OUT_DIR, outFile);
    const publicPath = `/carousel/${outFile}`;
    const fallback = {
      title: row.title,
      category: row.category,
      difficulty: row.difficulty,
      description: row.description,
    };

    try {
      const bytes = await readThumbnailBytes(row.thumbnail, fallback);
      await writeOptimizedWebp(bytes, outPath);
      console.log(`✓ ${row.slug}`);
    } catch (error) {
      fallbackCount += 1;
      console.warn(`! ${row.slug} fallback SVG`, error);
      const bytes = decodeDataUrl(generateLessonThumbnailDataUrl(fallback));
      await writeOptimizedWebp(bytes, outPath);
    }

    manifest.push({
      id,
      title: row.title,
      category: row.category,
      difficulty: row.difficulty,
      estimatedMinutes: row.estimatedMinutes,
      description: row.description,
      thumbnail: publicPath,
      totalXp: row.quizXp + row.masteryXpPerQuestion * row.questionsPerAttempt,
      sectionCount: row.sectionCount,
      subsectionCount: row.subsectionCount,
    });
  }

  await writeFile(MANIFEST_PATH, formatManifest(manifest), "utf8");

  const keep = new Set(manifest.map((lesson) => path.basename(lesson.thumbnail)));
  for (const file of await readdir(OUT_DIR)) {
    if (!file.endsWith(".webp") || keep.has(file)) {
      continue;
    }
    await unlink(path.join(OUT_DIR, file));
  }

  console.log(`\nWrote ${manifest.length} published lessons to public/carousel/`);
  if (fallbackCount > 0) {
    console.log(`  ${fallbackCount} used SVG fallback (missing thumbnail in DB)`);
  }
  console.log(`Wrote manifest to src/lib/landing/carousel-manifest.ts`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
