import type { MoveDefinition, MoveId } from "@adamsaxion/pricewar-types";
import { COFFEE_SHOP_SCENARIO_ID } from "@adamsaxion/pricewar-types";

const id = (s: string) => s as MoveId;

export const COFFEE_SHOP_MOVES: MoveDefinition[] = [
  {
    id: id("sales.set_price"),
    domain: "sales",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Set price",
    description: "Update your menu price for the next round.",
    kind: "oneShot",
    input: { kind: "slider", min: 100, max: 800, step: 25, unit: "¢" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["currentPrice"],
  },
  {
    id: id("sales.flash_sale"),
    domain: "sales",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Flash sale",
    description: "Temporary price cut to drive volume this round.",
    kind: "oneShot",
    input: { kind: "slider", min: 5, max: 30, step: 5, unit: "% off" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["currentPrice", "reputation"],
  },
  {
    id: id("marketing.run_ad_campaign"),
    domain: "marketing",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Run ad campaign",
    description: "Boost brand awareness and reputation.",
    kind: "oneShot",
    input: { kind: "amount", min: 50, max: 500, currency: "$" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["reputation", "cash"],
  },
  {
    id: id("marketing.social_post"),
    domain: "marketing",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Social media push",
    description: "Low-cost brand bump via social channels.",
    kind: "oneShot",
    input: { kind: "amount", min: 25, max: 150, currency: "$" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["reputation", "cash"],
  },
  {
    id: id("marketing.loyalty_cards"),
    domain: "marketing",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Loyalty cards",
    description: "Invest in repeat-customer program.",
    kind: "oneShot",
    input: { kind: "amount", min: 75, max: 300, currency: "$" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["reputation", "cash"],
  },
  {
    id: id("procurement.buy_beans"),
    domain: "procurement",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Buy beans",
    description: "Increase inventory for the next round.",
    kind: "oneShot",
    input: { kind: "stepper", min: 10, max: 200, step: 10 },
    visibility: "private",
    timing: "preEvents",
    modifies: ["inventory", "cash"],
  },
  {
    id: id("procurement.hire_barista"),
    domain: "procurement",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Hire barista",
    description: "Add staff to handle more demand.",
    kind: "oneShot",
    input: { kind: "stepper", min: 1, max: 3, step: 1 },
    visibility: "private",
    timing: "preEvents",
    modifies: ["staffCount", "cash"],
  },
  {
    id: id("operations.deep_clean"),
    domain: "operations",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Deep clean",
    description: "Improve shop quality and morale.",
    kind: "oneShot",
    input: { kind: "amount", min: 50, max: 200, currency: "$" },
    visibility: "private",
    timing: "preEvents",
    modifies: ["morale", "reputation", "cash"],
  },
  {
    id: id("operations.extend_hours"),
    domain: "operations",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Extend hours",
    description: "Stay open longer to capture evening demand.",
    kind: "oneShot",
    input: { kind: "toggle", default: true },
    visibility: "public",
    timing: "preEvents",
    modifies: ["morale", "cash"],
  },
  {
    id: id("finance.emergency_loan"),
    domain: "finance",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Emergency loan",
    description: "Borrow cash now; pay interest next round.",
    kind: "oneShot",
    input: { kind: "amount", min: 200, max: 1000, currency: "$" },
    visibility: "private",
    timing: "preEvents",
    modifies: ["cash"],
  },
  {
    id: id("finance.pay_suppliers"),
    domain: "finance",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Pay suppliers early",
    description: "Prepay suppliers for a small reputation boost.",
    kind: "oneShot",
    input: { kind: "amount", min: 100, max: 400, currency: "$" },
    visibility: "private",
    timing: "preEvents",
    modifies: ["cash", "reputation"],
  },
  {
    id: id("sales.premium_blend"),
    domain: "sales",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Premium blend",
    description: "Launch a higher-margin specialty drink line.",
    kind: "oneShot",
    input: { kind: "amount", min: 150, max: 500, currency: "$" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["currentPrice", "reputation", "cash"],
  },
  {
    id: id("procurement.bulk_beans"),
    domain: "procurement",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Bulk bean order",
    description: "Volume discount on inventory restock.",
    kind: "oneShot",
    input: { kind: "stepper", min: 50, max: 300, step: 25 },
    visibility: "private",
    timing: "preEvents",
    modifies: ["inventory", "cash"],
  },
  {
    id: id("hr.cross_train"),
    domain: "hr",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Cross-train staff",
    description: "Improve flexibility and morale.",
    kind: "oneShot",
    input: { kind: "amount", min: 100, max: 350, currency: "$" },
    visibility: "private",
    timing: "preEvents",
    modifies: ["morale", "cash"],
  },
  {
    id: id("hr.raise_wages"),
    domain: "hr",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Raise wages",
    description: "Boost morale to reduce turnover risk.",
    kind: "oneShot",
    input: { kind: "amount", min: 200, max: 600, currency: "$" },
    visibility: "private",
    timing: "preEvents",
    modifies: ["morale", "cash"],
  },
  {
    id: id("marketing.local_partnership"),
    domain: "marketing",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Local partnership",
    description: "Co-market with a nearby business.",
    kind: "oneShot",
    input: { kind: "amount", min: 100, max: 400, currency: "$" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["reputation", "cash"],
  },
  {
    id: id("operations.menu_refresh"),
    domain: "operations",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Menu refresh",
    description: "Update signage and menu design.",
    kind: "oneShot",
    input: { kind: "amount", min: 75, max: 250, currency: "$" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["reputation", "cash"],
  },
  {
    id: id("sales.bundle_deal"),
    domain: "sales",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Bundle deal",
    description: "Coffee + pastry combo to lift average ticket.",
    kind: "oneShot",
    input: { kind: "amount", min: 50, max: 200, currency: "$" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["reputation", "cash"],
  },
  {
    id: id("marketing.influencer"),
    domain: "marketing",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Influencer collab",
    description: "Pay a local creator for a sponsored post.",
    kind: "oneShot",
    input: { kind: "amount", min: 150, max: 500, currency: "$" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["reputation", "cash"],
  },
  {
    id: id("marketing.free_samples"),
    domain: "marketing",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Free samples",
    description: "Hand out samples to foot traffic.",
    kind: "oneShot",
    input: { kind: "amount", min: 40, max: 180, currency: "$" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["reputation", "cash"],
  },
  {
    id: id("procurement.equipment_lease"),
    domain: "procurement",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Lease equipment",
    description: "Upgrade espresso machine via lease.",
    kind: "oneShot",
    input: { kind: "amount", min: 200, max: 600, currency: "$" },
    visibility: "private",
    timing: "preEvents",
    modifies: ["reputation", "cash"],
  },
  {
    id: id("operations.peak_staffing"),
    domain: "operations",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Peak staffing",
    description: "Add temp staff for rush hour coverage.",
    kind: "oneShot",
    input: { kind: "amount", min: 150, max: 450, currency: "$" },
    visibility: "private",
    timing: "preEvents",
    modifies: ["morale", "cash"],
  },
  {
    id: id("hr.hire_manager"),
    domain: "hr",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Hire shift manager",
    description: "Experienced manager improves operations.",
    kind: "oneShot",
    input: { kind: "amount", min: 350, max: 800, currency: "$" },
    visibility: "private",
    timing: "preEvents",
    modifies: ["morale", "staffCount", "cash"],
  },
  {
    id: id("finance.cash_reserve"),
    domain: "finance",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Build cash reserve",
    description: "Move cash to reserve (reduces risk next round).",
    kind: "oneShot",
    input: { kind: "amount", min: 100, max: 500, currency: "$" },
    visibility: "private",
    timing: "preEvents",
    modifies: ["cash"],
  },
  {
    id: id("sales.competitive_match"),
    domain: "sales",
    scenarios: [COFFEE_SHOP_SCENARIO_ID],
    name: "Match competitor price",
    description: "Undercut or match the rival's public price.",
    kind: "oneShot",
    input: { kind: "slider", min: 100, max: 800, step: 25, unit: "¢" },
    visibility: "public",
    timing: "preEvents",
    modifies: ["currentPrice"],
  },
];

export const MOVE_BY_ID = new Map<MoveId, MoveDefinition>(
  COFFEE_SHOP_MOVES.map((m) => [m.id, m])
);
