import type { ActionCatalogEntry } from "./catalog-types";

export const ACTION_CATALOG_DATA: ActionCatalogEntry[] = [
  {
    "id": "sales.s01",
    "spreadsheetCode": "S01",
    "domain": "sales",
    "name": "Set price",
    "tagline": "Set your menu price. Customers compare you to your rival next round.",
    "mechanic": "Choose your price per cup; your margin and price tier update right away.",
    "strongWhen": "You have solid quality and can win customers without racing to the bottom.",
    "riskyWhen": "Your rival undercuts you or your costs make the new price unprofitable.",
    "actionType": "Continuous (slider)",
    "visibility": "public",
    "inputKind": "slider",
    "immediateEffect": "Your price, margin per cup, and price tier update this round.",
    "delayedEffect": "Next round, customers split between you and your rival based on the new price.",
    "duration": "Until changed again. Price persists if not adjusted.",
    "prerequisite": "Always available"
  },
  {
    "id": "sales.s02",
    "spreadsheetCode": "S02",
    "domain": "sales",
    "name": "Expand menu",
    "tagline": "Add another drink to the menu. More choice can mean more revenue per customer.",
    "mechanic": "Add one menu item; revenue per customer can rise, but a bigger menu is harder to run well.",
    "strongWhen": "Your team is skilled enough to handle a wider menu without quality slipping.",
    "riskyWhen": "Your team is stretched thin; quality may drop and customers need a round to notice the new item.",
    "actionType": "Discrete (+1 menu item)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "Your menu grows by one item and revenue per customer may increase.",
    "delayedEffect": "If your team cannot keep up, quality may fall; customers take about a round to discover the new offering.",
    "duration": "Permanent until reversed (S03)",
    "prerequisite": "Team skill supports your current menu size. Cash at least $50. Maximum 5 menu items."
  },
  {
    "id": "sales.s03",
    "spreadsheetCode": "S03",
    "domain": "sales",
    "name": "Simplify menu",
    "tagline": "Drop a menu item and focus the team on doing fewer things well.",
    "mechanic": "Remove one menu item; less complexity can help quality recover.",
    "strongWhen": "Your menu has been hurting quality or slowing service.",
    "riskyWhen": "You lose the extra revenue per customer that a wider menu provided.",
    "actionType": "Discrete (-1 menu item)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "Your menu shrinks by one item and revenue per customer may decrease.",
    "delayedEffect": "Quality may improve if menu complexity was holding you back.",
    "duration": "Permanent until reversed (S02)",
    "prerequisite": "You must have more than one menu item"
  },
  {
    "id": "sales.s04",
    "spreadsheetCode": "S04",
    "domain": "sales",
    "name": "Flash sale",
    "tagline": "Slash prices for one round to pull in foot traffic and new customers.",
    "mechanic": "Drop your price 40% this round only and boost foot traffic by 25%.",
    "strongWhen": "You have capacity to serve a rush and can afford the margin hit.",
    "riskyWhen": "Your rival sees the price drop; new customers may not stick around without follow-up.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Your price drops 40% this round and foot traffic jumps 25%, drawing many new customers.",
    "delayedEffect": "Some new customers may become regulars; your rival noticed the sale.",
    "duration": "1 round only. Price auto-reverts next round.",
    "prerequisite": "You have cash to survive the margin hit. Cannot run two flash sales in a row."
  },
  {
    "id": "sales.s05",
    "spreadsheetCode": "S05",
    "domain": "sales",
    "name": "Price match guarantee",
    "tagline": "Promise to match your rival's price next round so they cannot undercut you.",
    "mechanic": "Announce a price match; next round your price automatically follows theirs.",
    "strongWhen": "You expect your rival to cut price and you want to stay competitive without guessing.",
    "riskyWhen": "You give up control of pricing and may match a price that hurts your margins.",
    "actionType": "Commitment",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "You publicly announce that you will match whatever your rival charges next round.",
    "delayedEffect": "Next round your price auto-matches theirs; you cannot set a different price that round.",
    "duration": "2 rounds (announcement + execution)",
    "prerequisite": "Always available"
  },
  {
    "id": "sales.s06",
    "spreadsheetCode": "S06",
    "domain": "sales",
    "name": "Premium positioning",
    "tagline": "Hold premium prices and attract customers who care about quality over deals.",
    "mechanic": "Lock your price tier to premium or luxury with a floor at 1.5 times the market average.",
    "strongWhen": "Your reputation and quality justify higher prices and a loyal regular base.",
    "riskyWhen": "Price-sensitive casuals walk away; you cannot drop below the premium floor while active.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Your price tier locks to premium or luxury; you cannot price below 1.5 times market average.",
    "delayedEffect": "You attract quality-seeking customers, lose price-sensitive casuals, and shift toward regulars.",
    "duration": "Persists until deactivated",
    "prerequisite": "Reputation at least 0.6"
  },
  {
    "id": "sales.s07",
    "spreadsheetCode": "S07",
    "domain": "sales",
    "name": "Bundle offer",
    "tagline": "Sell a combo of menu items at a 15% discount for three rounds.",
    "mechanic": "Create a bundle of two or more items at 15% off; some customers spend more, others spend less per item.",
    "strongWhen": "You have at least two menu items and customers often buy more than one drink.",
    "riskyWhen": "Too many customers switch from full-price singles to the discounted bundle.",
    "actionType": "Temporary (3 rounds)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "A bundle of two or more menu items goes live at 15% off.",
    "delayedEffect": "Total revenue rises or falls depending on how many customers upgrade to the bundle.",
    "duration": "3 rounds then expires. Can renew.",
    "prerequisite": "At least 2 menu items. Cash at least $30."
  },
  {
    "id": "sales.s08",
    "spreadsheetCode": "S08",
    "domain": "sales",
    "name": "Surge pricing",
    "tagline": "Automatically raise prices 20% when foot traffic spikes from events or marketing.",
    "mechanic": "Set a rule: if foot traffic exceeds a threshold this round, your price rises 20%.",
    "strongWhen": "You expect a busy round from marketing or a local event and want to capture extra revenue.",
    "riskyWhen": "Customers may feel gouged; satisfaction can drop if they think the price is poor value.",
    "actionType": "Conditional trigger",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Surge pricing activates if foot traffic is high enough this round.",
    "delayedEffect": "You capture windfall revenue during busy periods, but customers may react negatively.",
    "duration": "1 round (triggers only if condition met)",
    "prerequisite": "Always available"
  },
  {
    "id": "procurement.p01",
    "spreadsheetCode": "P01",
    "domain": "procurement",
    "name": "Upgrade supplier tier",
    "tagline": "Switch to better beans. Higher cost, but better quality in your cup.",
    "mechanic": "Move up one supplier tier; input costs rise and product quality improves.",
    "strongWhen": "You can afford higher ongoing costs and want to build reputation through quality.",
    "riskyWhen": "Cash is tight; the full quality boost takes one to two rounds to show up.",
    "actionType": "Discrete (+1 tier)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "Your supplier tier rises, input costs increase, and quality starts improving.",
    "delayedEffect": "Reputation builds faster from better inputs; full quality effect takes one to two rounds.",
    "duration": "Permanent until changed",
    "prerequisite": "Cash sufficient to cover higher ongoing input costs. Cannot exceed tier 5."
  },
  {
    "id": "procurement.p02",
    "spreadsheetCode": "P02",
    "domain": "procurement",
    "name": "Downgrade supplier tier",
    "tagline": "Cut bean costs by switching to a cheaper supplier.",
    "mechanic": "Move down one supplier tier; input costs fall and product quality drops.",
    "strongWhen": "You need immediate cost relief and quality is already strong enough to absorb a hit.",
    "riskyWhen": "Quality and reputation erode; customers notice over two to three rounds.",
    "actionType": "Discrete (-1 tier)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "Your supplier tier drops, input costs decrease, and quality falls.",
    "delayedEffect": "Reputation starts decaying from lower quality; customer behavior shifts over two to three rounds.",
    "duration": "Permanent until changed",
    "prerequisite": "Supplier tier above 1"
  },
  {
    "id": "procurement.p03",
    "spreadsheetCode": "P03",
    "domain": "procurement",
    "name": "Increase inventory buffer",
    "tagline": "Stock up on beans. Costs money now, but saves you when supply gets tight.",
    "mechanic": "Add two rounds of backup supply; pay upfront for extra resilience.",
    "strongWhen": "You expect supply disruptions or want insurance before a risky stretch.",
    "riskyWhen": "Cash is tied up with no immediate revenue return unless a disruption actually hits.",
    "actionType": "Discrete (+2 rounds of supply)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "Your inventory buffer grows by two rounds of supply; cash decreases by the buffer cost.",
    "delayedEffect": "No revenue boost on its own; value shows up only if a supply disruption hits.",
    "duration": "Permanent until changed",
    "prerequisite": "Cash at least equal to buffer cost"
  },
  {
    "id": "procurement.p04",
    "spreadsheetCode": "P04",
    "domain": "procurement",
    "name": "Reduce inventory buffer",
    "tagline": "Free up cash by running leaner on bean stock.",
    "mechanic": "Remove two rounds of backup supply and recover the cash tied up in inventory.",
    "strongWhen": "You need cash now and supply has been stable.",
    "riskyWhen": "A supply disruption hits and you face a cost spike and possible quality drop.",
    "actionType": "Discrete (-2 rounds of supply)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "Your inventory buffer shrinks by two rounds and cash increases from freed buffer cost.",
    "delayedEffect": "If supply breaks down, you absorb the full hit with no backup stock.",
    "duration": "Permanent until changed",
    "prerequisite": "Inventory buffer above 0"
  },
  {
    "id": "procurement.p05",
    "spreadsheetCode": "P05",
    "domain": "procurement",
    "name": "Exclusive supplier deal",
    "tagline": "Lock in a top-tier supplier for yourself and block your rival from the best beans.",
    "mechanic": "Secure an exclusive tier 4 supplier for the rest of the match; your supply reliability jumps to 98%.",
    "strongWhen": "Your rival depends on premium inputs and you can afford the upfront cost.",
    "riskyWhen": "You spend heavily upfront; the payoff depends on how much your rival relied on top suppliers.",
    "actionType": "One-shot (per match)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "You lock in an exclusive tier 4 supplier; your rival cannot access tier 4 or 5 suppliers.",
    "delayedEffect": "Your rival's maximum quality is capped; your supply chain is nearly immune to disruptions.",
    "duration": "Rest of match",
    "prerequisite": "Cash at least $100. Supplier tier at least 3. Once per match only."
  },
  {
    "id": "procurement.p06",
    "spreadsheetCode": "P06",
    "domain": "procurement",
    "name": "Negotiate bulk discount",
    "tagline": "Cut input costs 10% for four rounds by locking in a bulk deal with your current supplier.",
    "mechanic": "Input costs drop 10% for four rounds after you negotiate with a supplier you have kept steady.",
    "strongWhen": "You have stayed with the same supplier tier for three or more rounds and volume is steady.",
    "riskyWhen": "The discount expires after four rounds and costs revert unless you renegotiate.",
    "actionType": "Temporary (4 rounds)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Your input costs drop 10% for the next four rounds.",
    "delayedEffect": "After four rounds costs return to normal; you can negotiate again if eligible.",
    "duration": "4 rounds",
    "prerequisite": "Same supplier tier for 3+ consecutive rounds. Cash at least $20."
  },
  {
    "id": "procurement.p07",
    "spreadsheetCode": "P07",
    "domain": "procurement",
    "name": "Source locally",
    "tagline": "Switch to local beans; costs and quality shift depending on where your shop sits.",
    "mechanic": "Change sourcing to local suppliers; cost and quality effects vary by location.",
    "strongWhen": "Your location favors local sourcing, such as lower costs in rural areas or higher quality downtown.",
    "riskyWhen": "The wrong location pairing raises costs or cuts quality; reliability varies by area.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "You switch to local sourcing; costs and quality adjust based on your location.",
    "delayedEffect": "Supply reliability and brand perception may shift over time depending on your area.",
    "duration": "Persists until switched back",
    "prerequisite": "Always available"
  },
  {
    "id": "operations.o01",
    "spreadsheetCode": "O01",
    "domain": "operations",
    "name": "Set deployment: speed mode",
    "tagline": "Push the team to serve faster. More cups out the door, less polish per customer.",
    "mechanic": "Staff prioritize speed over craft; you serve more customers with a weaker experience each.",
    "strongWhen": "Demand exceeds your normal capacity and you need to capture every sale this round.",
    "riskyWhen": "Customer satisfaction drops; regulars may notice the rushed service.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Your team shifts to speed mode: higher throughput, lower experience per customer.",
    "delayedEffect": "You capture revenue that would have been lost to long lines, but satisfaction suffers.",
    "duration": "Persists until changed to another mode",
    "prerequisite": "Always available"
  },
  {
    "id": "operations.o02",
    "spreadsheetCode": "O02",
    "domain": "operations",
    "name": "Set deployment: quality mode",
    "tagline": "Slow down and focus on craft. Fewer customers, but each cup is better.",
    "mechanic": "Staff prioritize presentation and quality; fewer customers served, better experience each.",
    "strongWhen": "You are building reputation and your regulars value consistency over speed.",
    "riskyWhen": "High demand means you turn customers away at the door.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Your team shifts to quality mode: fewer customers served, better experience per cup.",
    "delayedEffect": "Reputation builds faster and regulars stay happier, but capacity drops.",
    "duration": "Persists until changed",
    "prerequisite": "Always available"
  },
  {
    "id": "operations.o03",
    "spreadsheetCode": "O03",
    "domain": "operations",
    "name": "Set deployment: balanced mode",
    "tagline": "Run a steady shop with no special push toward speed or craft.",
    "mechanic": "Default operating mode with no bonuses or penalties.",
    "strongWhen": "You want a neutral baseline without committing to speed, quality, or service extremes.",
    "riskyWhen": "You miss the upside of a focused mode when conditions favor speed or quality.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Your team returns to balanced mode with no special bonuses or penalties.",
    "delayedEffect": "Steady performance with no compounding gains from a focused deployment.",
    "duration": "Persists until changed",
    "prerequisite": "Always available"
  },
  {
    "id": "operations.o04",
    "spreadsheetCode": "O04",
    "domain": "operations",
    "name": "Set deployment: customer focus",
    "tagline": "Train the team on hospitality: greetings, remembering regulars, and atmosphere.",
    "mechanic": "Staff prioritize customer interaction over production speed or craft alone.",
    "strongWhen": "You have at least two staff and want to convert casuals into loyal regulars.",
    "riskyWhen": "Production slows if your team is too thin to cover both service and the bar.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Your team shifts to customer focus: stronger service and atmosphere this round.",
    "delayedEffect": "Satisfaction and regular conversion improve more than in quality mode alone.",
    "duration": "Persists until changed",
    "prerequisite": "At least 2 staff (one on production while others focus on customers)"
  },
  {
    "id": "operations.o05",
    "spreadsheetCode": "O05",
    "domain": "operations",
    "name": "Upgrade equipment",
    "tagline": "Invest in better gear. More capacity and quality, but gear wears down without upkeep.",
    "mechanic": "Upgrade equipment one level; capacity per worker rises and waste drops.",
    "strongWhen": "You have cash for the upgrade and plan to maintain the equipment over time.",
    "riskyWhen": "You skip maintenance; equipment loses one level every six rounds without upkeep.",
    "actionType": "One-shot (with cooldown)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Equipment upgrade begins; full benefit arrives next round.",
    "delayedEffect": "Permanent capacity and quality gains, but gear depreciates every six rounds without maintenance.",
    "duration": "Permanent (but depreciates)",
    "prerequisite": "Cash at least $80. Cannot upgrade during previous upgrade installation. Max level 5."
  },
  {
    "id": "operations.o06",
    "spreadsheetCode": "O06",
    "domain": "operations",
    "name": "Perform maintenance",
    "tagline": "Service your equipment before it degrades. Cheaper than buying another upgrade.",
    "mechanic": "Reset the equipment wear timer and prevent the next level drop.",
    "strongWhen": "Your equipment is level 2 or above and approaching its next depreciation cycle.",
    "riskyWhen": "You spend on maintenance when cash is needed elsewhere for growth.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Equipment depreciation timer resets; your gear keeps its current level.",
    "delayedEffect": "Without regular maintenance, equipment drops one level every six rounds.",
    "duration": "Resets depreciation timer",
    "prerequisite": "Equipment level at least 2 (level 1 is baseline and does not degrade)"
  },
  {
    "id": "operations.o07",
    "spreadsheetCode": "O07",
    "domain": "operations",
    "name": "Start R&D project",
    "tagline": "Fund a research project over several rounds for a chance at a big breakthrough.",
    "mechanic": "Launch a 3 to 5 round project; success odds improve with higher team skill.",
    "strongWhen": "Your team is skilled, you have spare cash, and no other project is running.",
    "riskyWhen": "Projects can fail; you lose the investment and morale takes a small hit.",
    "actionType": "Multi-round commitment",
    "visibility": "private",
    "inputKind": "singleChoice",
    "immediateEffect": "An R&D project starts; it runs for 3 to 5 rounds with a 40% to 70% success chance.",
    "delayedEffect": "Success brings a quality boost, new menu item, or cost cut; failure loses your investment.",
    "duration": "3-5 rounds to complete",
    "prerequisite": "No active R&D project. Cash covers project cost. At least 2 staff to keep the shop running."
  },
  {
    "id": "operations.o08",
    "spreadsheetCode": "O08",
    "domain": "operations",
    "name": "Activate overtime",
    "tagline": "Push staff for one round of extra capacity. Higher wages, lower morale afterward.",
    "mechanic": "Boost total capacity 30% this round only; wage costs rise 50% for the round.",
    "strongWhen": "Demand spikes this round and morale is healthy enough to absorb the strain.",
    "riskyWhen": "Morale drops and you cannot use overtime again if morale is too low or you ran it two rounds in a row.",
    "actionType": "One-shot (1 round)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Capacity rises 30% this round; wage costs increase 50%.",
    "delayedEffect": "Morale takes a hit that persists; consecutive overtime is blocked.",
    "duration": "1 round only",
    "prerequisite": "Team morale at least 0.3. Not used last round (no consecutive overtime)."
  },
  {
    "id": "hr.h01",
    "spreadsheetCode": "H01",
    "domain": "hr",
    "name": "Hire worker",
    "tagline": "Bring on another barista. More capacity, but the new hire starts below your team average.",
    "mechanic": "Add one worker; capacity rises but average team skill drops until they ramp up.",
    "strongWhen": "You need capacity and can afford the hiring cost while the new hire learns.",
    "riskyWhen": "Average skill dips immediately; the hire takes two to three rounds to reach team level without training.",
    "actionType": "Discrete (+1 worker)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "Staff count rises by one; cash decreases and average team skill drops slightly.",
    "delayedEffect": "The new worker's skill grows over time, especially with training investment.",
    "duration": "Permanent (until fired or quit)",
    "prerequisite": "Cash covers hiring cost. Worker starts next round."
  },
  {
    "id": "hr.h02",
    "spreadsheetCode": "H02",
    "domain": "hr",
    "name": "Fire worker",
    "tagline": "Let your weakest worker go. Saves wages, but morale and capacity take a hit.",
    "mechanic": "Remove one worker; your lowest-skilled staff member leaves unless you specify otherwise.",
    "strongWhen": "You are overstaffed or need to cut costs and can absorb the capacity loss.",
    "riskyWhen": "Remaining staff morale drops; repeated firings compound the damage and may cause overflow.",
    "actionType": "Discrete (-1 worker)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "Staff count drops by one; capacity falls and you pay severance.",
    "delayedEffect": "Morale among remaining staff drops; multiple firings in a row make it worse.",
    "duration": "Permanent",
    "prerequisite": "More than one worker (cannot fire your last staff member)"
  },
  {
    "id": "hr.h03",
    "spreadsheetCode": "H03",
    "domain": "hr",
    "name": "Raise wages",
    "tagline": "Pay staff more to boost morale and reduce the chance they quit or get poached.",
    "mechanic": "Increase pay per worker; wage satisfaction and morale improve.",
    "strongWhen": "Morale is slipping, poaching is a threat, or union pressure is building.",
    "riskyWhen": "Higher ongoing wage costs strain cash if revenue does not keep up.",
    "actionType": "Continuous (+$1-$10 per worker)",
    "visibility": "private",
    "inputKind": "amount",
    "immediateEffect": "Wages rise; staff satisfaction and morale improve immediately.",
    "delayedEffect": "Staff become harder to poach, union risk eases, and service quality benefits from better morale.",
    "duration": "Permanent until changed",
    "prerequisite": "Cash sufficient to cover higher ongoing wages"
  },
  {
    "id": "hr.h04",
    "spreadsheetCode": "H04",
    "domain": "hr",
    "name": "Cut wages",
    "tagline": "Trim payroll to free up cash, but staff satisfaction will fall.",
    "mechanic": "Lower pay per worker; wage satisfaction and morale drop.",
    "strongWhen": "You need short-term cost relief and morale is still high enough to absorb a cut.",
    "riskyWhen": "Wages far below the local benchmark spike quit risk; staying low for three or more rounds builds union risk.",
    "actionType": "Continuous (-$1-$10 per worker)",
    "visibility": "private",
    "inputKind": "amount",
    "immediateEffect": "Wages fall; staff satisfaction and morale drop immediately.",
    "delayedEffect": "Quit risk rises sharply if pay stays well below local norms; prolonged cuts raise union risk.",
    "duration": "Permanent until changed",
    "prerequisite": "Wages stay above minimum wage"
  },
  {
    "id": "hr.h05",
    "spreadsheetCode": "H05",
    "domain": "hr",
    "name": "Invest in training",
    "tagline": "Fund ongoing training to grow team skill over several rounds.",
    "mechanic": "Set a per-round training budget; team skill rises each round while funded.",
    "strongWhen": "You have cash to invest and want better quality, less waste, and menu flexibility over time.",
    "riskyWhen": "Results take three to four rounds of sustained spending before they feel significant.",
    "actionType": "Continuous ($10-$100 per round)",
    "visibility": "private",
    "inputKind": "amount",
    "immediateEffect": "Training budget is set; team skill begins improving each round.",
    "delayedEffect": "Higher skill means better quality, less waste, more capacity, and support for a wider menu.",
    "duration": "Ongoing while funded. Set to $0 to stop.",
    "prerequisite": "Cash covers training amount per round"
  },
  {
    "id": "hr.h06",
    "spreadsheetCode": "H06",
    "domain": "hr",
    "name": "Stop training",
    "tagline": "Cut the training budget and save cash each round.",
    "mechanic": "Set training spending to zero; cost savings start immediately.",
    "strongWhen": "You need to preserve cash and current skill levels are strong enough for now.",
    "riskyWhen": "Team skill slowly decays without any training investment.",
    "actionType": "Discrete (set to $0)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "Training spending stops; you save the training cost this round.",
    "delayedEffect": "Team skill erodes slowly each round without training.",
    "duration": "Permanent until training restarted",
    "prerequisite": "Training budget currently above $0"
  },
  {
    "id": "hr.h07",
    "spreadsheetCode": "H07",
    "domain": "hr",
    "name": "Poach competitor's staff",
    "tagline": "Try to hire an experienced worker away from your rival.",
    "mechanic": "Attempt to poach one of your opponent's workers; success is not guaranteed.",
    "strongWhen": "You have cash for the poach fee and wages, and your rival's team is stronger than yours.",
    "riskyWhen": "Failure alerts your rival; success helps you but may invite retaliation.",
    "actionType": "One-shot competitive action",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "You attempt to hire one of your rival's workers.",
    "delayedEffect": "On success your team skill jumps and theirs drops; on failure your rival is alerted.",
    "duration": "Instant resolution",
    "prerequisite": "Cash at least $60 plus wage for the hire. Once every 3 rounds."
  },
  {
    "id": "hr.h08",
    "spreadsheetCode": "H08",
    "domain": "hr",
    "name": "Restructure team",
    "tagline": "Spread skill more evenly across the team so no one person carries everything.",
    "mechanic": "Redistribute skill across workers for a more balanced, uniform team.",
    "strongWhen": "You rely too heavily on one star worker or want to support a broader menu.",
    "riskyWhen": "Morale takes a temporary hit from the shake-up.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Skill is redistributed evenly across your team.",
    "delayedEffect": "You become less vulnerable to losing one key worker and can support a wider menu.",
    "duration": "Instant effect",
    "prerequisite": "At least 3 staff members"
  },
  {
    "id": "hr.h09",
    "spreadsheetCode": "H09",
    "domain": "hr",
    "name": "Performance bonus",
    "tagline": "Hand out a one-time cash bonus to lift morale for a few rounds.",
    "mechanic": "Pay all workers a lump sum; morale jumps immediately but fades over two to three rounds.",
    "strongWhen": "Morale needs a quick rescue and you have cash for a short-term boost.",
    "riskyWhen": "The lift is temporary and does not replace a real wage increase for long-term retention.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "All workers receive a one-time bonus; morale rises immediately.",
    "delayedEffect": "Morale boost fades over two to three rounds; quit risk still depends on base wages.",
    "duration": "Morale effect decays: +0.08 round 1, +0.05 round 2, +0.02 round 3, gone.",
    "prerequisite": "Cash at least $15 times staff count"
  },
  {
    "id": "marketing.m01",
    "spreadsheetCode": "M01",
    "domain": "marketing",
    "name": "Set marketing budget",
    "tagline": "Spend on ads and promotions to drive more foot traffic to your shop.",
    "mechanic": "Set a per-round marketing budget; higher spend brings more customers, with diminishing returns.",
    "strongWhen": "You have capacity to serve extra customers and cash to spend on growth.",
    "riskyWhen": "Each extra dollar buys less traffic; heavy spending over time reduces effectiveness.",
    "actionType": "Continuous ($0-$200)",
    "visibility": "private",
    "inputKind": "amount",
    "immediateEffect": "Your marketing budget is set; foot traffic rises based on spend this round.",
    "delayedEffect": "Sustained high spending yields diminishing returns as customers tune out repeated ads.",
    "duration": "Ongoing until adjusted",
    "prerequisite": "Cash covers chosen budget per round"
  },
  {
    "id": "marketing.m02",
    "spreadsheetCode": "M02",
    "domain": "marketing",
    "name": "Launch loyalty program",
    "tagline": "Reward repeat customers and slowly build a base of loyal regulars.",
    "mechanic": "Activate a loyalty program; customers earn rewards and regular conversion improves.",
    "strongWhen": "You have steady foot traffic and can afford the launch and ongoing per-customer cost.",
    "riskyWhen": "Ongoing cost scales with your customer base; payoff takes three to four rounds.",
    "actionType": "One-shot to activate",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Loyalty program goes live; customers start accumulating rewards.",
    "delayedEffect": "Over three to four rounds your customer mix shifts toward regulars who are less price-sensitive.",
    "duration": "Permanent until deactivated (M03)",
    "prerequisite": "Cash at least $40 launch cost. Ongoing cost equals your customers times $0.20 per round."
  },
  {
    "id": "marketing.m03",
    "spreadsheetCode": "M03",
    "domain": "marketing",
    "name": "Deactivate loyalty program",
    "tagline": "Shut down the loyalty program and stop the ongoing per-customer cost.",
    "mechanic": "Turn off the loyalty program; ongoing costs stop but loyalty benefits end.",
    "strongWhen": "The program cost outweighs the regular retention benefit or cash is tight.",
    "riskyWhen": "Regular conversion slows and your customer mix drifts back toward casuals.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Loyalty program shuts off; ongoing costs stop immediately.",
    "delayedEffect": "Your customer mix slowly shifts back toward casuals as loyalty benefits fade.",
    "duration": "Permanent until relaunched",
    "prerequisite": "Loyalty program must be active"
  },
  {
    "id": "marketing.m04",
    "spreadsheetCode": "M04",
    "domain": "marketing",
    "name": "Run targeted campaign",
    "tagline": "Run a two-round campaign aimed at one customer type: deal seekers, quality seekers, or new customers.",
    "mechanic": "Choose a segment to target; the campaign boosts that group more efficiently than general marketing.",
    "strongWhen": "You know which customer type you want to grow and can afford a focused push.",
    "riskyWhen": "Only one segment is affected; other customer types see no benefit.",
    "actionType": "One-shot (2 rounds)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "A targeted campaign launches for your chosen customer segment.",
    "delayedEffect": "That segment grows faster than it would from general marketing alone.",
    "duration": "2 rounds",
    "prerequisite": "Cash at least $50"
  },
  {
    "id": "marketing.m05",
    "spreadsheetCode": "M05",
    "domain": "marketing",
    "name": "Counter-marketing",
    "tagline": "Undercut your rival's last marketing push and capture a share of the traffic they generated.",
    "mechanic": "Neutralize 60% of your opponent's previous-round marketing effect.",
    "strongWhen": "Your rival spent heavily on marketing last round and you want to steal their audience.",
    "riskyWhen": "This does not bring new traffic on its own; it only works if they marketed recently.",
    "actionType": "One-shot reactive",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "You neutralize 60% of your rival's last-round marketing impact.",
    "delayedEffect": "Your share of the traffic they generated increases; their marketing ROI drops.",
    "duration": "1 round",
    "prerequisite": "Rival spent on marketing last round. Cash at least $30."
  },
  {
    "id": "marketing.m06",
    "spreadsheetCode": "M06",
    "domain": "marketing",
    "name": "Sponsor local event",
    "tagline": "Sponsor a neighborhood event for a big one-round traffic spike and a lasting reputation boost.",
    "mechanic": "Fund a local event; foot traffic on the street jumps 40% for one round.",
    "strongWhen": "You have capacity to handle a rush and want a reputation and brand lift in the community.",
    "riskyWhen": "Both shops benefit from the traffic spike; you pay the full sponsorship cost.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Street foot traffic spikes 40% this round; you gain a reputation boost and both shops see more customers.",
    "delayedEffect": "Reputation and brand gains persist beyond the event and build community presence.",
    "duration": "Traffic spike: 1 round. Brand/reputation: persistent",
    "prerequisite": "Cash at least $80"
  },
  {
    "id": "marketing.m07",
    "spreadsheetCode": "M07",
    "domain": "marketing",
    "name": "Rebrand",
    "tagline": "Reset your brand identity and get a fresh start on customer perception.",
    "mechanic": "Reset brand value to a baseline and gain a short-term reputation momentum boost.",
    "strongWhen": "You fixed past quality problems but your brand still reflects the old reputation.",
    "riskyWhen": "A strong existing brand gets reset downward; the move is available once per match.",
    "actionType": "One-shot (major)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Brand value resets to baseline; reputation gains a momentum boost.",
    "delayedEffect": "Elevated reputation momentum lasts about three rounds, accelerating recovery.",
    "duration": "Instant reset + 3 rounds of elevated momentum",
    "prerequisite": "Cash at least $120. Once per match only."
  },
  {
    "id": "finance.f01",
    "spreadsheetCode": "F01",
    "domain": "finance",
    "name": "Take loan",
    "tagline": "Borrow cash now and pay it back with interest over time.",
    "mechanic": "Add cash equal to the loan amount; debt and interest expenses begin accruing.",
    "strongWhen": "You have a clear investment that will pay off and room under your credit limit.",
    "riskyWhen": "Interest compounds, your credit limit shrinks as debt grows, and heavy debt raises austerity risk.",
    "actionType": "Discrete (amount chosen)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "Cash increases by the loan amount; debt rises by the same amount.",
    "delayedEffect": "Interest accrues each round; higher debt reduces future borrowing capacity.",
    "duration": "Until repaid (F02)",
    "prerequisite": "Loan amount within available credit limit. Credit limit above 0."
  },
  {
    "id": "finance.f02",
    "spreadsheetCode": "F02",
    "domain": "finance",
    "name": "Repay debt",
    "tagline": "Pay down debt to reduce interest and free up future borrowing room.",
    "mechanic": "Reduce debt by your chosen amount; interest and credit limit recalculate.",
    "strongWhen": "You have excess cash and interest is eating into margins.",
    "riskyWhen": "Cash spent on repayment is unavailable for operations or growth investments.",
    "actionType": "Discrete (amount chosen)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "Debt drops by the repayment amount; interest expense falls and credit limit rises.",
    "delayedEffect": "Less cash goes to interest; more borrowing capacity if you need it later.",
    "duration": "Instant",
    "prerequisite": "Cash covers repayment amount. Debt above 0."
  },
  {
    "id": "finance.f03",
    "spreadsheetCode": "F03",
    "domain": "finance",
    "name": "Cash reserve mode",
    "tagline": "Hunker down and preserve cash by blocking non-essential spending.",
    "mechanic": "Enter cash preservation mode; only basic operations, pricing, and HR adjustments are allowed.",
    "strongWhen": "Cash is dangerously low and you need to stop the bleeding.",
    "riskyWhen": "Your rival keeps investing while you sit still; competitive position may erode.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Non-essential spending is blocked; only core operations remain available.",
    "delayedEffect": "Cash accumulates faster, but you fall behind on growth and competitive moves.",
    "duration": "Persists until deactivated",
    "prerequisite": "Always available"
  },
  {
    "id": "finance.f04",
    "spreadsheetCode": "F04",
    "domain": "finance",
    "name": "Exit cash reserve mode",
    "tagline": "Leave cash preservation mode and unlock your full set of strategic moves.",
    "mechanic": "Deactivate cash reserve mode; all actions and normal spending become available again.",
    "strongWhen": "Cash is healthy enough to invest and compete again.",
    "riskyWhen": "Leaving too early may drain cash before you have a stable buffer.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "All actions unlock and normal spending is permitted again.",
    "delayedEffect": "Full strategic flexibility restored for growth and competitive play.",
    "duration": "Instant",
    "prerequisite": "Cash reserve mode must be active"
  },
  {
    "id": "finance.f05",
    "spreadsheetCode": "F05",
    "domain": "finance",
    "name": "Insurance purchase",
    "tagline": "Pay for insurance each round to halve the cash damage from bad events.",
    "mechanic": "Ongoing insurance reduces financial impact of negative events by 50%.",
    "strongWhen": "You face volatile conditions and want a safety net against costly surprises.",
    "riskyWhen": "Insurance does not stop events or protect morale and reputation, only cash losses.",
    "actionType": "Ongoing cost",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Insurance activates; financial damage from negative events is cut in half.",
    "delayedEffect": "Events still happen; only the cash hit is softened. Stop paying and coverage lapses.",
    "duration": "Persists while funded. Stop paying = coverage lapses.",
    "prerequisite": "Cash at least $15 per round"
  },
  {
    "id": "finance.f06",
    "spreadsheetCode": "F06",
    "domain": "finance",
    "name": "Declare dividend / profit-taking",
    "tagline": "Bank profit so it cannot be lost to events or bankruptcy.",
    "mechanic": "Move cash into secured profit that is safe from operational losses.",
    "strongWhen": "You are ahead and want to protect gains before a risky stretch.",
    "riskyWhen": "Banked cash leaves operations and cannot fund growth or emergencies.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Profit is banked as secured; cash on hand drops.",
    "delayedEffect": "Secured profit cannot be lost, but that cash is gone from day-to-day operations.",
    "duration": "Permanent (banked)",
    "prerequisite": "Cash above $50 minimum dividend. Not in austerity mode."
  },
  {
    "id": "finance.f07",
    "spreadsheetCode": "F07",
    "domain": "finance",
    "name": "Scout opponent",
    "tagline": "Pay for intel on one hidden aspect of your rival's business.",
    "mechanic": "Reveal one opponent attribute: cash, staff count, reputation, supplier tier, morale, or debt.",
    "strongWhen": "You are planning a competitive move and need to know where your rival is weak.",
    "riskyWhen": "Intel grows stale; confidence drops 20% each round after you acquire it.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "You learn one hidden fact about your rival's business.",
    "delayedEffect": "Intel stays on file but confidence decays each round; refresh before acting on old data.",
    "duration": "Intel acquired. Confidence decays 20% per round.",
    "prerequisite": "Cash at least $25. Choose which attribute to scout."
  }
];

// 46 actions
