import type { ActionCatalogEntry } from "./catalog-types";

export const ACTION_CATALOG_DATA: ActionCatalogEntry[] = [
  {
    "id": "sales.s01",
    "spreadsheetCode": "S01",
    "domain": "sales",
    "name": "Set price",
    "tagline": "Customer allocation shifts next round based on new price vs opponent.",
    "mechanic": "price_per_unit changes to selected value. price_tier recalculates. margin_per_unit recalculates.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Customer allocation shifts next round based on new price vs opponent.",
    "actionType": "Continuous (slider)",
    "visibility": "public",
    "inputKind": "slider",
    "immediateEffect": "price_per_unit changes to selected value. price_tier recalculates. margin_per_unit recalculates.",
    "delayedEffect": "Customer allocation shifts next round based on new price vs opponent.",
    "duration": "Until changed again. Price persists if not adjusted.",
    "prerequisite": "Always available"
  },
  {
    "id": "sales.s02",
    "spreadsheetCode": "S02",
    "domain": "sales",
    "name": "Expand menu",
    "tagline": "If staff skill is insufficient, product_quality drops via complexity penalty. Takes 1 round for customers to discover ne",
    "mechanic": "menu_breadth +1. revenue_per_customer increases (price discrimination enabled). menu_complexity_penalty recalculates.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "If staff skill is insufficient, product_quality drops via complexity penalty. Takes 1 round for customers to discover new offering.",
    "actionType": "Discrete (+1 menu item)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "menu_breadth +1. revenue_per_customer increases (price discrimination enabled). menu_complexity_penalty recalculates.",
    "delayedEffect": "If staff skill is insufficient, product_quality drops via complexity penalty. Takes 1 round for customers to discover new offering.",
    "duration": "Permanent until reversed (S03)",
    "prerequisite": "avg_skill >= menu_breadth \u00d7 0.2. Cash >= $50. Cannot expand beyond 5."
  },
  {
    "id": "sales.s03",
    "spreadsheetCode": "S03",
    "domain": "sales",
    "name": "Simplify menu",
    "tagline": "Quality may recover if complexity was the bottleneck.",
    "mechanic": "menu_breadth -1. menu_complexity_penalty reduces. revenue_per_customer decreases.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Quality may recover if complexity was the bottleneck.",
    "actionType": "Discrete (-1 menu item)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "menu_breadth -1. menu_complexity_penalty reduces. revenue_per_customer decreases.",
    "delayedEffect": "Quality may recover if complexity was the bottleneck.",
    "duration": "Permanent until reversed (S02)",
    "prerequisite": "menu_breadth > 1"
  },
  {
    "id": "sales.s04",
    "spreadsheetCode": "S04",
    "domain": "sales",
    "name": "Flash sale",
    "tagline": "New customers acquired may convert to casuals/regulars in subsequent rounds. Opponent sees the price drop.",
    "mechanic": "price_per_unit temporarily drops 40% this round ONLY. Foot traffic boost +25% for your shop. Draws segment_new heavily.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "New customers acquired may convert to casuals/regulars in subsequent rounds. Opponent sees the price drop.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "price_per_unit temporarily drops 40% this round ONLY. Foot traffic boost +25% for your shop. Draws segment_new heavily.",
    "delayedEffect": "New customers acquired may convert to casuals/regulars in subsequent rounds. Opponent sees the price drop.",
    "duration": "1 round only. Price auto-reverts next round.",
    "prerequisite": "Cash > $0 (must survive the margin hit). Cannot flash sale two rounds in a row."
  },
  {
    "id": "sales.s05",
    "spreadsheetCode": "S05",
    "domain": "sales",
    "name": "Price match guarantee",
    "tagline": "Next round, your price auto-matches opponent's price. You lose price-setting ability but guarantee you won't be undercut",
    "mechanic": "Publicly announces: 'I will match whatever my opponent charges next round.' Visible to opponent.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Next round, your price auto-matches opponent's price. You lose price-setting ability but guarantee you won't be undercut.",
    "actionType": "Commitment",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Publicly announces: 'I will match whatever my opponent charges next round.' Visible to opponent.",
    "delayedEffect": "Next round, your price auto-matches opponent's price. You lose price-setting ability but guarantee you won't be undercut.",
    "duration": "2 rounds (announcement + execution)",
    "prerequisite": "Always available"
  },
  {
    "id": "sales.s06",
    "spreadsheetCode": "S06",
    "domain": "sales",
    "name": "Premium positioning",
    "tagline": "Attracts quality-seeking customers. Repels price-sensitive casuals. Shifts segment composition toward regulars.",
    "mechanic": "price_tier locked to 'premium' or 'luxury'. Price floor set at 1.5x market average. Cannot drop below this while active.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Attracts quality-seeking customers. Repels price-sensitive casuals. Shifts segment composition toward regulars.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "price_tier locked to 'premium' or 'luxury'. Price floor set at 1.5x market average. Cannot drop below this while active.",
    "delayedEffect": "Attracts quality-seeking customers. Repels price-sensitive casuals. Shifts segment composition toward regulars.",
    "duration": "Persists until deactivated",
    "prerequisite": "Player.reputation >= 0.6"
  },
  {
    "id": "sales.s07",
    "spreadsheetCode": "S07",
    "domain": "sales",
    "name": "Bundle offer",
    "tagline": "Net effect on revenue depends on how many customers upgrade from single item to bundle. Can increase or decrease total r",
    "mechanic": "Creates a bundle of 2+ menu items at 15% discount. revenue_per_customer changes: some customers buy more at lower per-unit price.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Net effect on revenue depends on how many customers upgrade from single item to bundle. Can increase or decrease total revenue.",
    "actionType": "Temporary (3 rounds)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Creates a bundle of 2+ menu items at 15% discount. revenue_per_customer changes: some customers buy more at lower per-unit price.",
    "delayedEffect": "Net effect on revenue depends on how many customers upgrade from single item to bundle. Can increase or decrease total revenue.",
    "duration": "3 rounds then expires. Can renew.",
    "prerequisite": "menu_breadth >= 2. Cash >= $30."
  },
  {
    "id": "sales.s08",
    "spreadsheetCode": "S08",
    "domain": "sales",
    "name": "Surge pricing",
    "tagline": "Captures windfall revenue during high-traffic events. But customers may react negatively (satisfaction penalty if price_",
    "mechanic": "Sets a rule: if foot traffic exceeds X this round (from events/marketing), price auto-increases by 20%.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Captures windfall revenue during high-traffic events. But customers may react negatively (satisfaction penalty if price_value_perception drops).",
    "actionType": "Conditional trigger",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Sets a rule: if foot traffic exceeds X this round (from events/marketing), price auto-increases by 20%.",
    "delayedEffect": "Captures windfall revenue during high-traffic events. But customers may react negatively (satisfaction penalty if price_value_perception drops).",
    "duration": "1 round (triggers only if condition met)",
    "prerequisite": "Always available"
  },
  {
    "id": "procurement.p01",
    "spreadsheetCode": "P01",
    "domain": "procurement",
    "name": "Upgrade supplier tier",
    "tagline": "Reputation builds faster from higher quality inputs. Takes 1-2 rounds for full quality effect.",
    "mechanic": "supplier_tier +1. effective_input_cost increases. product_quality increases (supplier component).",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Reputation builds faster from higher quality inputs. Takes 1-2 rounds for full quality effect.",
    "actionType": "Discrete (+1 tier)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "supplier_tier +1. effective_input_cost increases. product_quality increases (supplier component).",
    "delayedEffect": "Reputation builds faster from higher quality inputs. Takes 1-2 rounds for full quality effect.",
    "duration": "Permanent until changed",
    "prerequisite": "Cash sufficient to cover higher ongoing input costs. Cannot exceed tier 5."
  },
  {
    "id": "procurement.p02",
    "spreadsheetCode": "P02",
    "domain": "procurement",
    "name": "Downgrade supplier tier",
    "tagline": "Reputation starts decaying from lower quality. Takes 2-3 rounds to fully manifest in customer behavior.",
    "mechanic": "supplier_tier -1. effective_input_cost decreases. product_quality decreases.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Reputation starts decaying from lower quality. Takes 2-3 rounds to fully manifest in customer behavior.",
    "actionType": "Discrete (-1 tier)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "supplier_tier -1. effective_input_cost decreases. product_quality decreases.",
    "delayedEffect": "Reputation starts decaying from lower quality. Takes 2-3 rounds to fully manifest in customer behavior.",
    "duration": "Permanent until changed",
    "prerequisite": "supplier_tier > 1"
  },
  {
    "id": "procurement.p03",
    "spreadsheetCode": "P03",
    "domain": "procurement",
    "name": "Increase inventory buffer",
    "tagline": "No direct revenue effect. Insurance value only realized when a disruption hits.",
    "mechanic": "inventory_buffer +2. Cash decreases by buffer cost. Resilience to supply disruptions increases.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "No direct revenue effect. Insurance value only realized when a disruption hits.",
    "actionType": "Discrete (+2 rounds of supply)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "inventory_buffer +2. Cash decreases by buffer cost. Resilience to supply disruptions increases.",
    "delayedEffect": "No direct revenue effect. Insurance value only realized when a disruption hits.",
    "duration": "Permanent until changed",
    "prerequisite": "Cash >= buffer cost"
  },
  {
    "id": "procurement.p04",
    "spreadsheetCode": "P04",
    "domain": "procurement",
    "name": "Reduce inventory buffer",
    "tagline": "If a supply disruption hits, you eat the full cost (input_cost spike, potential quality drop).",
    "mechanic": "inventory_buffer -2. Cash increases by freed buffer cost. Disruption resilience decreases.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "If a supply disruption hits, you eat the full cost (input_cost spike, potential quality drop).",
    "actionType": "Discrete (-2 rounds of supply)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "inventory_buffer -2. Cash increases by freed buffer cost. Disruption resilience decreases.",
    "delayedEffect": "If a supply disruption hits, you eat the full cost (input_cost spike, potential quality drop).",
    "duration": "Permanent until changed",
    "prerequisite": "inventory_buffer > 0"
  },
  {
    "id": "procurement.p05",
    "spreadsheetCode": "P05",
    "domain": "procurement",
    "name": "Exclusive supplier deal",
    "tagline": "Opponent's maximum product_quality is capped. Your supply chain is near-immune to disruptions. Massive competitive advan",
    "mechanic": "Locks in a tier 4 supplier exclusively. Opponent cannot access tier 4 or 5 suppliers for the rest of the match. Your supply_reliability increases to 0.98.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Opponent's maximum product_quality is capped. Your supply chain is near-immune to disruptions. Massive competitive advantage if opponent was relying on premium inputs.",
    "actionType": "One-shot (per match)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Locks in a tier 4 supplier exclusively. Opponent cannot access tier 4 or 5 suppliers for the rest of the match. Your supply_reliability increases to 0.98.",
    "delayedEffect": "Opponent's maximum product_quality is capped. Your supply chain is near-immune to disruptions. Massive competitive advantage if opponent was relying on premium inputs.",
    "duration": "Rest of match",
    "prerequisite": "Cash >= $100. supplier_tier >= 3. Can only be used ONCE per match."
  },
  {
    "id": "procurement.p06",
    "spreadsheetCode": "P06",
    "domain": "procurement",
    "name": "Negotiate bulk discount",
    "tagline": "After 4 rounds, cost reverts to normal. Can renegotiate.",
    "mechanic": "effective_input_cost reduced by 10% for 4 rounds.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "After 4 rounds, cost reverts to normal. Can renegotiate.",
    "actionType": "Temporary (4 rounds)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "effective_input_cost reduced by 10% for 4 rounds.",
    "delayedEffect": "After 4 rounds, cost reverts to normal. Can renegotiate.",
    "duration": "4 rounds",
    "prerequisite": "Same supplier tier for 3+ consecutive rounds. Cash >= $20."
  },
  {
    "id": "procurement.p07",
    "spreadsheetCode": "P07",
    "domain": "procurement",
    "name": "Source locally",
    "tagline": "Affects supply_reliability (local = more reliable in some locations, less in others). May affect brand_value (local sour",
    "mechanic": "Switches to local sourcing. In rural/farm: cost -15%, quality -5%. In downtown: cost +10%, quality +5%. In developing nation: cost -25%, quality -15%.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Affects supply_reliability (local = more reliable in some locations, less in others). May affect brand_value (local sourcing as marketing).",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Switches to local sourcing. In rural/farm: cost -15%, quality -5%. In downtown: cost +10%, quality +5%. In developing nation: cost -25%, quality -15%.",
    "delayedEffect": "Affects supply_reliability (local = more reliable in some locations, less in others). May affect brand_value (local sourcing as marketing).",
    "duration": "Persists until switched back",
    "prerequisite": "Always available"
  },
  {
    "id": "operations.o01",
    "spreadsheetCode": "O01",
    "domain": "operations",
    "name": "Set deployment: speed mode",
    "tagline": "If demand exceeds normal capacity, speed mode captures revenue that would otherwise be lost. But satisfaction drops.",
    "mechanic": "Staff prioritize throughput over quality. Serve more customers, lower experience per customer.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "If demand exceeds normal capacity, speed mode captures revenue that would otherwise be lost. But satisfaction drops.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Staff prioritize throughput over quality. Serve more customers, lower experience per customer.",
    "delayedEffect": "If demand exceeds normal capacity, speed mode captures revenue that would otherwise be lost. But satisfaction drops.",
    "duration": "Persists until changed to another mode",
    "prerequisite": "Always available"
  },
  {
    "id": "operations.o02",
    "spreadsheetCode": "O02",
    "domain": "operations",
    "name": "Set deployment: quality mode",
    "tagline": "Reputation builds faster. Regulars more satisfied. But you may turn away customers at the door if demand exceeds reduced",
    "mechanic": "Staff prioritize craft and presentation. Fewer customers served, better experience.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Reputation builds faster. Regulars more satisfied. But you may turn away customers at the door if demand exceeds reduced capacity.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Staff prioritize craft and presentation. Fewer customers served, better experience.",
    "delayedEffect": "Reputation builds faster. Regulars more satisfied. But you may turn away customers at the door if demand exceeds reduced capacity.",
    "duration": "Persists until changed",
    "prerequisite": "Always available"
  },
  {
    "id": "operations.o03",
    "spreadsheetCode": "O03",
    "domain": "operations",
    "name": "Set deployment: balanced mode",
    "tagline": "Neutral baseline.",
    "mechanic": "Default mode. No bonuses or penalties.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Neutral baseline.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Default mode. No bonuses or penalties.",
    "delayedEffect": "Neutral baseline.",
    "duration": "Persists until changed",
    "prerequisite": "Always available"
  },
  {
    "id": "operations.o04",
    "spreadsheetCode": "O04",
    "domain": "operations",
    "name": "Set deployment: customer focus",
    "tagline": "Strong effect on satisfaction and regular conversion. Service quality spike is larger than quality mode.",
    "mechanic": "Staff prioritize customer interaction: greeting, remembering regulars, creating atmosphere.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Strong effect on satisfaction and regular conversion. Service quality spike is larger than quality mode.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Staff prioritize customer interaction: greeting, remembering regulars, creating atmosphere.",
    "delayedEffect": "Strong effect on satisfaction and regular conversion. Service quality spike is larger than quality mode.",
    "duration": "Persists until changed",
    "prerequisite": "staff_count >= 2 (need someone on production while others focus on customers)"
  },
  {
    "id": "operations.o05",
    "spreadsheetCode": "O05",
    "domain": "operations",
    "name": "Upgrade equipment",
    "tagline": "Permanent capacity and quality improvement. Depreciates 1 level every 6 rounds without maintenance.",
    "mechanic": "capital_equipment_level +1 (next round). Capacity_per_worker increases. Product_quality gets equipment bonus. Waste_rate decreases.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Permanent capacity and quality improvement. Depreciates 1 level every 6 rounds without maintenance.",
    "actionType": "One-shot (with cooldown)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "capital_equipment_level +1 (next round). Capacity_per_worker increases. Product_quality gets equipment bonus. Waste_rate decreases.",
    "delayedEffect": "Permanent capacity and quality improvement. Depreciates 1 level every 6 rounds without maintenance.",
    "duration": "Permanent (but depreciates)",
    "prerequisite": "Cash >= $80. Cannot upgrade during installation of previous upgrade. Max level 5."
  },
  {
    "id": "operations.o06",
    "spreadsheetCode": "O06",
    "domain": "operations",
    "name": "Perform maintenance",
    "tagline": "Without maintenance, equipment degrades every 6 rounds. Maintenance is cheaper than re-upgrading.",
    "mechanic": "Resets equipment depreciation timer. Prevents equipment level from dropping next depreciation cycle.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Without maintenance, equipment degrades every 6 rounds. Maintenance is cheaper than re-upgrading.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Resets equipment depreciation timer. Prevents equipment level from dropping next depreciation cycle.",
    "delayedEffect": "Without maintenance, equipment degrades every 6 rounds. Maintenance is cheaper than re-upgrading.",
    "duration": "Resets depreciation timer",
    "prerequisite": "capital_equipment_level >= 2 (level 1 is baseline, doesn't degrade)"
  },
  {
    "id": "operations.o07",
    "spreadsheetCode": "O07",
    "domain": "operations",
    "name": "Start R&D project",
    "tagline": "On completion: success = major payoff (quality boost, new menu item, or cost reduction). Failure = investment lost, smal",
    "mechanic": "innovation_project created with type, rounds_remaining (3-5), and success_prob (40-70% base, +10% if avg_skill > 0.6).",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "On completion: success = major payoff (quality boost, new menu item, or cost reduction). Failure = investment lost, small morale hit.",
    "actionType": "Multi-round commitment",
    "visibility": "private",
    "inputKind": "singleChoice",
    "immediateEffect": "innovation_project created with type, rounds_remaining (3-5), and success_prob (40-70% base, +10% if avg_skill > 0.6).",
    "delayedEffect": "On completion: success = major payoff (quality boost, new menu item, or cost reduction). Failure = investment lost, small morale hit.",
    "duration": "3-5 rounds to complete",
    "prerequisite": "No active innovation_project. Cash >= project cost. staff_count >= 2 (need someone to keep the shop running)."
  },
  {
    "id": "operations.o08",
    "spreadsheetCode": "O08",
    "domain": "operations",
    "name": "Activate overtime",
    "tagline": "Morale hit persists. Cannot use overtime again if morale < 0.3 or if used 2 consecutive rounds.",
    "mechanic": "total_capacity +30% for this round only. Wage expense increases by 50% this round.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Morale hit persists. Cannot use overtime again if morale < 0.3 or if used 2 consecutive rounds.",
    "actionType": "One-shot (1 round)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "total_capacity +30% for this round only. Wage expense increases by 50% this round.",
    "delayedEffect": "Morale hit persists. Cannot use overtime again if morale < 0.3 or if used 2 consecutive rounds.",
    "duration": "1 round only",
    "prerequisite": "avg_morale >= 0.3. Not used previous round (no consecutive overtime)."
  },
  {
    "id": "hr.h01",
    "spreadsheetCode": "H01",
    "domain": "hr",
    "name": "Hire worker",
    "tagline": "New worker's skill grows over time with training. Takes 2-3 rounds to reach team average without training investment.",
    "mechanic": "staff_count +1. Cash decreases by hiring cost. avg_skill recalculates (pulled down by new hire). total_capacity increases.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "New worker's skill grows over time with training. Takes 2-3 rounds to reach team average without training investment.",
    "actionType": "Discrete (+1 worker)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "staff_count +1. Cash decreases by hiring cost. avg_skill recalculates (pulled down by new hire). total_capacity increases.",
    "delayedEffect": "New worker's skill grows over time with training. Takes 2-3 rounds to reach team average without training investment.",
    "duration": "Permanent (until fired or quit)",
    "prerequisite": "Cash >= hiring_cost. Effective next round (hiring process takes 1 round)."
  },
  {
    "id": "hr.h02",
    "spreadsheetCode": "H02",
    "domain": "hr",
    "name": "Fire worker",
    "tagline": "Remaining staff morale drops. If multiple firings in sequence, morale compounds downward. Capacity reduction may cause c",
    "mechanic": "staff_count -1. Worst-performing worker leaves (lowest skill unless specified). total_capacity decreases. Cash hit for severance.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Remaining staff morale drops. If multiple firings in sequence, morale compounds downward. Capacity reduction may cause customer overflow.",
    "actionType": "Discrete (-1 worker)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "staff_count -1. Worst-performing worker leaves (lowest skill unless specified). total_capacity decreases. Cash hit for severance.",
    "delayedEffect": "Remaining staff morale drops. If multiple firings in sequence, morale compounds downward. Capacity reduction may cause customer overflow.",
    "duration": "Permanent",
    "prerequisite": "staff_count > 1 (cannot fire last worker)"
  },
  {
    "id": "hr.h03",
    "spreadsheetCode": "H03",
    "domain": "hr",
    "name": "Raise wages",
    "tagline": "Staff become more resistant to poaching. Union risk decreases if it was building. Improved morale feeds service quality.",
    "mechanic": "wage_per_worker increases. wage_satisfaction recalculates (improves). avg_morale improves via wage_satisfaction component. quit_probability decreases.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Staff become more resistant to poaching. Union risk decreases if it was building. Improved morale feeds service quality.",
    "actionType": "Continuous (+$1-$10 per worker)",
    "visibility": "private",
    "inputKind": "amount",
    "immediateEffect": "wage_per_worker increases. wage_satisfaction recalculates (improves). avg_morale improves via wage_satisfaction component. quit_probability decreases.",
    "delayedEffect": "Staff become more resistant to poaching. Union risk decreases if it was building. Improved morale feeds service quality.",
    "duration": "Permanent until changed",
    "prerequisite": "Cash sufficient to cover higher ongoing wages"
  },
  {
    "id": "hr.h04",
    "spreadsheetCode": "H04",
    "domain": "hr",
    "name": "Cut wages",
    "tagline": "If wages drop below Environment.wage_benchmark \u00d7 0.8: quit_probability spikes. If below for 3+ rounds: union_risk accumu",
    "mechanic": "wage_per_worker decreases. wage_satisfaction recalculates (worsens). avg_morale drops via wage component. quit_probability increases.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "If wages drop below Environment.wage_benchmark \u00d7 0.8: quit_probability spikes. If below for 3+ rounds: union_risk accumulates. Cascade risk.",
    "actionType": "Continuous (-$1-$10 per worker)",
    "visibility": "private",
    "inputKind": "amount",
    "immediateEffect": "wage_per_worker decreases. wage_satisfaction recalculates (worsens). avg_morale drops via wage component. quit_probability increases.",
    "delayedEffect": "If wages drop below Environment.wage_benchmark \u00d7 0.8: quit_probability spikes. If below for 3+ rounds: union_risk accumulates. Cascade risk.",
    "duration": "Permanent until changed",
    "prerequisite": "wage_per_worker > config.minimum_wage"
  },
  {
    "id": "hr.h05",
    "spreadsheetCode": "H05",
    "domain": "hr",
    "name": "Invest in training",
    "tagline": "Skill compounds over rounds. Higher skill = better quality, less waste, higher capacity, can support broader menu. Takes",
    "mechanic": "training_investment set to chosen level. avg_skill increases by training_investment \u00d7 0.005 per round (diminishing returns above current skill).",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Skill compounds over rounds. Higher skill = better quality, less waste, higher capacity, can support broader menu. Takes 3-4 rounds of sustained investment to see significant results.",
    "actionType": "Continuous ($10-$100 per round)",
    "visibility": "private",
    "inputKind": "amount",
    "immediateEffect": "training_investment set to chosen level. avg_skill increases by training_investment \u00d7 0.005 per round (diminishing returns above current skill).",
    "delayedEffect": "Skill compounds over rounds. Higher skill = better quality, less waste, higher capacity, can support broader menu. Takes 3-4 rounds of sustained investment to see significant results.",
    "duration": "Ongoing while funded. Set to $0 to stop.",
    "prerequisite": "Cash >= training amount per round"
  },
  {
    "id": "hr.h06",
    "spreadsheetCode": "H06",
    "domain": "hr",
    "name": "Stop training",
    "tagline": "avg_skill decays by 0.01 per round without any training (skills atrophy). Slow but cumulative.",
    "mechanic": "training_investment set to $0. Cost savings immediate.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "avg_skill decays by 0.01 per round without any training (skills atrophy). Slow but cumulative.",
    "actionType": "Discrete (set to $0)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "training_investment set to $0. Cost savings immediate.",
    "delayedEffect": "avg_skill decays by 0.01 per round without any training (skills atrophy). Slow but cumulative.",
    "duration": "Permanent until training restarted",
    "prerequisite": "training_investment > 0"
  },
  {
    "id": "hr.h07",
    "spreadsheetCode": "H07",
    "domain": "hr",
    "name": "Poach competitor's staff",
    "tagline": "Success: your avg_skill jumps (experienced hire), opponent's drops. Opponent's morale drops (-0.05 contagion). Failure: ",
    "mechanic": "Attempt to hire one of opponent's workers. Success = your staff_count +1 (skilled worker, starts at 0.6 skill), opponent staff_count -1.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Success: your avg_skill jumps (experienced hire), opponent's drops. Opponent's morale drops (-0.05 contagion). Failure: opponent is alerted, may counter.",
    "actionType": "One-shot competitive action",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Attempt to hire one of opponent's workers. Success = your staff_count +1 (skilled worker, starts at 0.6 skill), opponent staff_count -1.",
    "delayedEffect": "Success: your avg_skill jumps (experienced hire), opponent's drops. Opponent's morale drops (-0.05 contagion). Failure: opponent is alerted, may counter.",
    "duration": "Instant resolution",
    "prerequisite": "Cash >= $60 + wage. Can only poach once every 3 rounds."
  },
  {
    "id": "hr.h08",
    "spreadsheetCode": "H08",
    "domain": "hr",
    "name": "Restructure team",
    "tagline": "Reduces vulnerability to losing one key worker. Enables broader menu support. But temporary morale hit.",
    "mechanic": "Redistribute skill across workers. Changes skill_distribution from current to 'uniform'. Smooths out capability gaps.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Reduces vulnerability to losing one key worker. Enables broader menu support. But temporary morale hit.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Redistribute skill across workers. Changes skill_distribution from current to 'uniform'. Smooths out capability gaps.",
    "delayedEffect": "Reduces vulnerability to losing one key worker. Enables broader menu support. But temporary morale hit.",
    "duration": "Instant effect",
    "prerequisite": "staff_count >= 3 (need enough people to restructure)"
  },
  {
    "id": "hr.h09",
    "spreadsheetCode": "H09",
    "domain": "hr",
    "name": "Performance bonus",
    "tagline": "Morale boost decays over 2-3 rounds (temporary). Does not change quit_probability threshold (wage-based). Good for short",
    "mechanic": "One-time cash payment to all workers. avg_morale +0.08 immediately. wage_satisfaction unaffected (bonus is not a raise).",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Morale boost decays over 2-3 rounds (temporary). Does not change quit_probability threshold (wage-based). Good for short-term morale rescue.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "One-time cash payment to all workers. avg_morale +0.08 immediately. wage_satisfaction unaffected (bonus is not a raise).",
    "delayedEffect": "Morale boost decays over 2-3 rounds (temporary). Does not change quit_probability threshold (wage-based). Good for short-term morale rescue.",
    "duration": "Morale effect decays: +0.08 round 1, +0.05 round 2, +0.02 round 3, gone.",
    "prerequisite": "Cash >= $15 \u00d7 staff_count"
  },
  {
    "id": "marketing.m01",
    "spreadsheetCode": "M01",
    "domain": "marketing",
    "name": "Set marketing budget",
    "tagline": "Diminishing returns: each additional dollar is less effective than the last. Cumulative spending reduces marketing_effec",
    "mechanic": "marketing_spend set to chosen level. Foot traffic modifier increases based on spend \u00d7 marketing_effectiveness.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Diminishing returns: each additional dollar is less effective than the last. Cumulative spending reduces marketing_effectiveness over time.",
    "actionType": "Continuous ($0-$200)",
    "visibility": "private",
    "inputKind": "amount",
    "immediateEffect": "marketing_spend set to chosen level. Foot traffic modifier increases based on spend \u00d7 marketing_effectiveness.",
    "delayedEffect": "Diminishing returns: each additional dollar is less effective than the last. Cumulative spending reduces marketing_effectiveness over time.",
    "duration": "Ongoing until adjusted",
    "prerequisite": "Cash >= chosen budget per round"
  },
  {
    "id": "marketing.m02",
    "spreadsheetCode": "M02",
    "domain": "marketing",
    "name": "Launch loyalty program",
    "tagline": "Over 3-4 rounds, segment composition shifts toward regulars. Regulars are less price-sensitive, creating pricing power.",
    "mechanic": "loyalty_program_active = true. Customers begin accumulating loyalty. conversion_to_regular rate increases by +0.03/round. churn_from_regular decreases by 0.02/round.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Over 3-4 rounds, segment composition shifts toward regulars. Regulars are less price-sensitive, creating pricing power.",
    "actionType": "One-shot to activate",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "loyalty_program_active = true. Customers begin accumulating loyalty. conversion_to_regular rate increases by +0.03/round. churn_from_regular decreases by 0.02/round.",
    "delayedEffect": "Over 3-4 rounds, segment composition shifts toward regulars. Regulars are less price-sensitive, creating pricing power.",
    "duration": "Permanent until deactivated (M03)",
    "prerequisite": "Cash >= $40 launch cost. Ongoing cost = your_customers \u00d7 $0.20/round."
  },
  {
    "id": "marketing.m03",
    "spreadsheetCode": "M03",
    "domain": "marketing",
    "name": "Deactivate loyalty program",
    "tagline": "Segment composition slowly shifts back toward casuals as the loyalty flywheel stops.",
    "mechanic": "loyalty_program_active = false. Ongoing cost stops. But loyalty benefits also stop accumulating.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Segment composition slowly shifts back toward casuals as the loyalty flywheel stops.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "loyalty_program_active = false. Ongoing cost stops. But loyalty benefits also stop accumulating.",
    "delayedEffect": "Segment composition slowly shifts back toward casuals as the loyalty flywheel stops.",
    "duration": "Permanent until relaunched",
    "prerequisite": "loyalty_program_active = true"
  },
  {
    "id": "marketing.m04",
    "spreadsheetCode": "M04",
    "domain": "marketing",
    "name": "Run targeted campaign",
    "tagline": "More efficient than general marketing for shifting segment composition. But only affects one segment.",
    "mechanic": "Targets a specific customer segment: choose 'value seekers' (boost casuals), 'quality seekers' (boost potential regulars), or 'new market' (boost segment_new).",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "More efficient than general marketing for shifting segment composition. But only affects one segment.",
    "actionType": "One-shot (2 rounds)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Targets a specific customer segment: choose 'value seekers' (boost casuals), 'quality seekers' (boost potential regulars), or 'new market' (boost segment_new).",
    "delayedEffect": "More efficient than general marketing for shifting segment composition. But only affects one segment.",
    "duration": "2 rounds",
    "prerequisite": "Cash >= $50"
  },
  {
    "id": "marketing.m05",
    "spreadsheetCode": "M05",
    "domain": "marketing",
    "name": "Counter-marketing",
    "tagline": "Denies opponent the ROI on their marketing spend. Does not generate new traffic itself.",
    "mechanic": "Neutralizes 60% of opponent's last-round marketing effect. Your share of their generated traffic increases.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Denies opponent the ROI on their marketing spend. Does not generate new traffic itself.",
    "actionType": "One-shot reactive",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Neutralizes 60% of opponent's last-round marketing effect. Your share of their generated traffic increases.",
    "delayedEffect": "Denies opponent the ROI on their marketing spend. Does not generate new traffic itself.",
    "duration": "1 round",
    "prerequisite": "Opponent's marketing_spend last round > $0. Cash >= $30."
  },
  {
    "id": "marketing.m06",
    "spreadsheetCode": "M06",
    "domain": "marketing",
    "name": "Sponsor local event",
    "tagline": "Reputation and brand boost persist beyond the event. Establishes community presence.",
    "mechanic": "Creates a 1-round foot traffic spike of +40% for the street. Both shops benefit but you get +15% reputation boost. Brand_value +0.05.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Reputation and brand boost persist beyond the event. Establishes community presence.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Creates a 1-round foot traffic spike of +40% for the street. Both shops benefit but you get +15% reputation boost. Brand_value +0.05.",
    "delayedEffect": "Reputation and brand boost persist beyond the event. Establishes community presence.",
    "duration": "Traffic spike: 1 round. Brand/reputation: persistent",
    "prerequisite": "Cash >= $80"
  },
  {
    "id": "marketing.m07",
    "spreadsheetCode": "M07",
    "domain": "marketing",
    "name": "Rebrand",
    "tagline": "A hard reset on brand. Useful if your brand_value decayed from past quality problems and you have since fixed them. The ",
    "mechanic": "brand_value resets to 0.15 (if higher, it drops; if lower, it rises). review_score unchanged. reputation gets a momentum boost (+0.1 to momentum).",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "A hard reset on brand. Useful if your brand_value decayed from past quality problems and you have since fixed them. The momentum boost accelerates reputation recovery.",
    "actionType": "One-shot (major)",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "brand_value resets to 0.15 (if higher, it drops; if lower, it rises). review_score unchanged. reputation gets a momentum boost (+0.1 to momentum).",
    "delayedEffect": "A hard reset on brand. Useful if your brand_value decayed from past quality problems and you have since fixed them. The momentum boost accelerates reputation recovery.",
    "duration": "Instant reset + 3 rounds of elevated momentum",
    "prerequisite": "Cash >= $120. Only available once per match."
  },
  {
    "id": "finance.f01",
    "spreadsheetCode": "F01",
    "domain": "finance",
    "name": "Take loan",
    "tagline": "Interest compounds. Credit_limit decreases as debt increases. Austerity risk increases if debt becomes unsustainable.",
    "mechanic": "cash += loan amount. debt += loan amount. interest_expense begins accruing.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Interest compounds. Credit_limit decreases as debt increases. Austerity risk increases if debt becomes unsustainable.",
    "actionType": "Discrete (amount chosen)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "cash += loan amount. debt += loan amount. interest_expense begins accruing.",
    "delayedEffect": "Interest compounds. Credit_limit decreases as debt increases. Austerity risk increases if debt becomes unsustainable.",
    "duration": "Until repaid (F02)",
    "prerequisite": "Loan amount <= credit_limit - current debt. credit_limit > 0."
  },
  {
    "id": "finance.f02",
    "spreadsheetCode": "F02",
    "domain": "finance",
    "name": "Repay debt",
    "tagline": "Freed from interest burden. More cash available for operations. Credit restored for future borrowing if needed.",
    "mechanic": "debt -= repayment amount. interest_expense recalculates lower. credit_limit recalculates higher.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Freed from interest burden. More cash available for operations. Credit restored for future borrowing if needed.",
    "actionType": "Discrete (amount chosen)",
    "visibility": "private",
    "inputKind": "stepper",
    "immediateEffect": "debt -= repayment amount. interest_expense recalculates lower. credit_limit recalculates higher.",
    "delayedEffect": "Freed from interest burden. More cash available for operations. Credit restored for future borrowing if needed.",
    "duration": "Instant",
    "prerequisite": "Cash >= repayment amount. Debt > 0."
  },
  {
    "id": "finance.f03",
    "spreadsheetCode": "F03",
    "domain": "finance",
    "name": "Cash reserve mode",
    "tagline": "Cash accumulates faster. But competitive position may erode as opponent invests.",
    "mechanic": "Signals to the engine that the player is prioritizing cash preservation. All non-essential spending blocked. Only basic operations, pricing, and HR adjustments allowed.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Cash accumulates faster. But competitive position may erode as opponent invests.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "Signals to the engine that the player is prioritizing cash preservation. All non-essential spending blocked. Only basic operations, pricing, and HR adjustments allowed.",
    "delayedEffect": "Cash accumulates faster. But competitive position may erode as opponent invests.",
    "duration": "Persists until deactivated",
    "prerequisite": "Always available"
  },
  {
    "id": "finance.f04",
    "spreadsheetCode": "F04",
    "domain": "finance",
    "name": "Exit cash reserve mode",
    "tagline": "Full strategic flexibility restored.",
    "mechanic": "All actions become available again. Normal spending permitted.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Full strategic flexibility restored.",
    "actionType": "Mode switch",
    "visibility": "private",
    "inputKind": "mode",
    "immediateEffect": "All actions become available again. Normal spending permitted.",
    "delayedEffect": "Full strategic flexibility restored.",
    "duration": "Instant",
    "prerequisite": "Cash reserve mode must be active"
  },
  {
    "id": "finance.f05",
    "spreadsheetCode": "F05",
    "domain": "finance",
    "name": "Insurance purchase",
    "tagline": "Does not prevent events from happening. Just reduces the cash damage. Does not affect non-financial event effects (moral",
    "mechanic": "Reduces the financial impact of negative stochastic events by 50%. Supply disruption cost halved. Fine amounts halved. Weather impact on revenue halved.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Does not prevent events from happening. Just reduces the cash damage. Does not affect non-financial event effects (morale, reputation).",
    "actionType": "Ongoing cost",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Reduces the financial impact of negative stochastic events by 50%. Supply disruption cost halved. Fine amounts halved. Weather impact on revenue halved.",
    "delayedEffect": "Does not prevent events from happening. Just reduces the cash damage. Does not affect non-financial event effects (morale, reputation).",
    "duration": "Persists while funded. Stop paying = coverage lapses.",
    "prerequisite": "Cash >= $15/round"
  },
  {
    "id": "finance.f06",
    "spreadsheetCode": "F06",
    "domain": "finance",
    "name": "Declare dividend / profit-taking",
    "tagline": "Secured profit cannot be lost to events or bankruptcy. But the cash is gone from operations.",
    "mechanic": "In scenarios where the objective is cumulative profit, this 'banks' profit as secured. In austerity scenarios, reduces cash on hand.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Secured profit cannot be lost to events or bankruptcy. But the cash is gone from operations.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "In scenarios where the objective is cumulative profit, this 'banks' profit as secured. In austerity scenarios, reduces cash on hand.",
    "delayedEffect": "Secured profit cannot be lost to events or bankruptcy. But the cash is gone from operations.",
    "duration": "Permanent (banked)",
    "prerequisite": "Cash > $50 (minimum dividend). Not in austerity mode."
  },
  {
    "id": "finance.f07",
    "spreadsheetCode": "F07",
    "domain": "finance",
    "name": "Scout opponent",
    "tagline": "Information persists in your opponent_intel with a confidence level that decays over rounds (stale info). Can be used to",
    "mechanic": "Reveals one hidden attribute of opponent's business. Choose from: cash level, staff count, reputation score, supplier tier, morale level, or debt level.",
    "strongWhen": "Favorable when your capacity, cash, and market conditions align.",
    "riskyWhen": "Information persists in your opponent_intel with a confidence level that decays over rounds (stale info). Can be used to time competitive actions.",
    "actionType": "One-shot",
    "visibility": "private",
    "inputKind": "toggle",
    "immediateEffect": "Reveals one hidden attribute of opponent's business. Choose from: cash level, staff count, reputation score, supplier tier, morale level, or debt level.",
    "delayedEffect": "Information persists in your opponent_intel with a confidence level that decays over rounds (stale info). Can be used to time competitive actions.",
    "duration": "Intel acquired. Confidence decays 20% per round.",
    "prerequisite": "Cash >= $25. Must choose which attribute to scout."
  }
];

// 46 actions
