export const COFFEE_SHOP_BALANCING = {
  startingCash: 5000,
  startingInventory: 200,
  startingStaffCount: 2,
  startingReputation: 50,
  startingMorale: 70,
  startingPrice: 350,
  basePerRoundCost: 200,
  staffWagePerRound: 150,
  inventoryCarryCostPerUnit: 0.5,
  beanCostPerUnit: 3,
  marketTotalDemandBase: 400,
  marketWeatherSensitivity: 0.2,
  marketPriceElasticity: -1.5,
  marketBrandWeight: 0.3,
  marketStockoutPenalty: 0.5,
  bankruptcyCashThreshold: 0,
  bankruptcyConsecutiveRounds: 2,
  victoryFinalCashWeight: 0.7,
  victoryFinalBrandWeight: 0.3,
} as const;
