/** Legacy balancing record on ScenarioConfig + pipeline defaults. */
export const COFFEE_SHOP_BALANCING = {
  startingCash: 500,
  startingInventory: 200,
  startingStaffCount: 3,
  startingReputation: 30,
  startingMorale: 70,
  startingPrice: 450,
  basePerRoundCost: 20,
  staffWagePerRound: 15,
  inventoryCarryCostPerUnit: 0.5,
  beanCostPerUnit: 0.2,
  marketTotalDemandBase: 100,
  marketWeatherSensitivity: 0.2,
  marketPriceElasticity: 1.2,
  marketBrandWeight: 0.3,
  marketStockoutPenalty: 0.5,
  bankruptcyCashThreshold: 0,
  bankruptcyConsecutiveRounds: 2,
  victoryFinalCashWeight: 0.7,
  victoryFinalBrandWeight: 0.3,
} as const;
